version: "3"
services:
  payhere-backend:
    container_name: payhere-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - payhere_deploy_db 
    restart: always
    environment:
      SQL_HOST: payhere_deploy_db 
      SQL_PORT: 5432
      DJANGO_SETTINGS_MODULE: my_settings
    env_file:
      - .dockerenv.deploy.backend
    command: 
      - bash 
      - -c 
      - | 
        /wait_for_db_connected -t 120 
        python manage.py migrate
        python manage.py collectstatic
        gunicorn payhere.wsgi:application --bind 0.0.0.0:8000
    volumes: 
      - .:/usr/src/app/ 

  payhere_deploy_db:
    container_name: payhere_deploy_db
    user: "1000:50"
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: payhere_deploy_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
      MYSQL_ROOT_PASSWORD: rootpass
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/data:/var/lib/mysql