# Generated by Django 4.0.1 on 2022-01-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payhereapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Deleted'),
        ),
    ]
